package com.example.framework.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.framework.dao.TouTiaoMessageGreenBean;

import com.example.framework.dao.TouTiaoMessageGreenBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig touTiaoMessageGreenBeanDaoConfig;

    private final TouTiaoMessageGreenBeanDao touTiaoMessageGreenBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        touTiaoMessageGreenBeanDaoConfig = daoConfigMap.get(TouTiaoMessageGreenBeanDao.class).clone();
        touTiaoMessageGreenBeanDaoConfig.initIdentityScope(type);

        touTiaoMessageGreenBeanDao = new TouTiaoMessageGreenBeanDao(touTiaoMessageGreenBeanDaoConfig, this);

        registerDao(TouTiaoMessageGreenBean.class, touTiaoMessageGreenBeanDao);
    }
    
    public void clear() {
        touTiaoMessageGreenBeanDaoConfig.clearIdentityScope();
    }

    public TouTiaoMessageGreenBeanDao getTouTiaoMessageGreenBeanDao() {
        return touTiaoMessageGreenBeanDao;
    }

}
